
[build]
  base = "client"
  publish = "client/build"
  command = "yarn run build"

[context.production]
  [context.production.environment]
    ELM_APP_API_URL="https://api.parliament.bobwhitelock.co.uk"
